### ISSUE TITLE
how to draw multiple pattern at once and showing them 

### ISSUE THREAD

**Issue by deepikakapila-1991** [itsxtt/pattern-lock#3]
![multiplePattern](https://user-images.githubusercontent.com/58063870/73910641-ed9dd800-48d5-11ea-9e99-3c47efaa0c35.png)

I want to create 3, 5 patterns at once, please suggest me is it possible using pattern-lock.
for reference i have attached the image.

Thanks :)

**Comment by l7naive** [comment]
Sorry, this library do not support this feature.

![1634180132372](https://user-images.githubusercontent.com/15245853/137243036-ff7dbd7b-42fd-4af4-8c03-9abd5dcf7485.jpg)
Try not invoke onFinish() when ACTION_UP.
